# Base de datos H2 almacenada temporalmente en memoria
spring.datasource.url=jdbc:h2:mem:esperadigital;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Usuario predeterminado de H2
spring.datasource.username=sa

# H2 sin contraseña
spring.datasource.password=

# Driver de conexión de H2
spring.datasource.driver-class-name=org.h2.Driver

# Dialecto de Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2
spring.h2.console.enabled=true

# Ruta para ingresar a la consola H2
spring.h2.console.path=/h2-console