# Configuración de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurante
spring.datasource.username=postgres
spring.datasource.password=ERIK140704

# Driver y Hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actualización automática del esquema (opcional)
spring.jpa.hibernate.ddl-auto=update
Rspring.jpa.show-sql=true